/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	// Activate GPIOD clock
	uint32_t *const pCtrlClck = (uint32_t*)0x40023830;
	*pCtrlClck |= (1 << 3);

	// Set the mode of pins
	uint32_t *const pGpiodMode = (uint32_t*)0x40020C00;
	*pGpiodMode &= ~(0xFF); // clear all pins
	*pGpiodMode |= 0x55; // set 0-3 pins as output.

	// Set the Pull up mode enable of input pins
	uint32_t *const pGpiodPullUp = (uint32_t*)0x40020C0C;
	*pGpiodPullUp &= 0x0; // clear all pins
	*pGpiodPullUp |= 0x00005500; // Enable 4-8 pins' pull up registers

	uint32_t volatile *const pGpiodOut = (uint32_t*)0x40020C14; // output of rows
	uint32_t volatile *const pGpiodIn  = (uint32_t*)0x40020C10;

	while(1)
	{
		*pGpiodOut |= 0x0000000F; // all outputs are high
		*pGpiodOut &= 0x0000000E; // row 1 is low

		uint8_t pin_status = (uint8_t) (*pGpiodIn & 0x1); // read pin1
		if (pin_status == 1)
		{
			printf("1 is pressed!\n");
		}
		/*
		for(uint8_t i = 1; i <= 4; i++)
		{
			uint8_t pin_status = (uint8_t) (*pGpiodIn & 0xi); // read pin1
			if pin_status ==
		}
		*/

	}
}
